### ISSUE TITLE
Provide simple input simulations

### ISSUE THREAD

**Issue by damonge** [simonsobs/BBPipe#12]
To start the development of bbpower we'd like to have some simple mock data. Ideally, to separate bugs from errors in the methodology, we'd like these sims to be as simple as possible: Gaussian foregrounds, signal and noise, with constant spectral indices.

Generating O(100-1000) and putting them somewhere at NERSC would be good.

**Comment by zonca** [comment]
@damonge do you have preference between CAR or HEALPix maps?

**Comment by damonge** [comment]
@zonca : for immediate work HEALPix would be best (since most of the code we've used in the past doesn't use CAR), but the plan is to support CAR too. Thanks!

**Comment by damonge** [comment]
Closing, since I think we've moved past this
